"""empty message

Revision ID: 10ea9f214b8e
Revises: 
Create Date: 2019-07-27 15:45:17.008245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10ea9f214b8e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('text_entry')
    op.drop_table('starred_entry')
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=50), nullable=True),
    sa.Column('password', sa.VARCHAR(length=100), nullable=True),
    sa.Column('secret_q', sa.VARCHAR(length=255), nullable=True),
    sa.Column('secret_q_ans', sa.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('starred_entry',
    sa.Column('owner_id', sa.INTEGER(), nullable=True),
    sa.Column('entry_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['entry_id'], ['text_entry.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], )
    )
    op.create_table('text_entry',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('body', sa.TEXT(length=2555), nullable=True),
    sa.Column('name', sa.VARCHAR(length=255), nullable=True),
    sa.Column('created_date', sa.DATETIME(), nullable=True),
    sa.Column('link', sa.VARCHAR(length=155), nullable=True),
    sa.Column('publicity', sa.BOOLEAN(), nullable=True),
    sa.Column('expires_on', sa.DATETIME(), nullable=True),
    sa.CheckConstraint('publicity IN (0, 1)'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('link')
    )
    # ### end Alembic commands ###
