"""empty message

Revision ID: 7a250851acbb
Revises: 
Create Date: 2019-07-29 18:21:51.001720

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a250851acbb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('password', sa.String(length=100), nullable=True),
    sa.Column('secret_q', sa.String(length=255), nullable=True),
    sa.Column('secret_q_ans', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('text_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('body', sa.Text(length=2555), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('link', sa.String(length=155), nullable=True),
    sa.Column('publicity', sa.Boolean(), nullable=True),
    sa.Column('expires_on', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('link')
    )
    op.create_table('starred_entry',
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('entry_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['entry_id'], ['text_entry.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('starred_entry')
    op.drop_table('text_entry')
    op.drop_table('user')
    # ### end Alembic commands ###
